### ISSUE TITLE
Python node methods do not follow PEP 8 naming conventions

### ISSUE THREAD

**Issue by jellehierck** [ika-rwth-aachen/ros2-pkg-create#12]
ROS 2 follows the PEP 8 guidelines for code style in Python (https://docs.ros.org/en/rolling/The-ROS2-Project/Contributing/Code-Style-Language-Versions.html#python).

PEP 8 prescribes snake_case for variable and function names (peps.python.org/pep-0008/#function-and-variable-names), but the generated Python nodes use camelCase.

I was actually thinking of going through the templates and fixing some style-related issues using Ruff, to match the code style that ROS 2 recommends and contribute any changes necessary, if that is something that you are interested.

The most basic ROS rules are defined by the following `ruff.toml` file:

```toml
# Assume a maximum line length of 100 characters.
# https://docs.ros.org/en/rolling/The-ROS2-Project/Contributing/Code-Style-Language-Versions.html#id4
line-length = 100

# Assume Python 3.8 or higher as this is the minimum for ROS 2 Humble on Windows (3.10 on Ubuntu)
# https://www.ros.org/reps/rep-2000.html#id48
target-version = "py38"

[format]
# Assume single quotes as per the ROS style recommendations.
# https://docs.ros.org/en/rolling/The-ROS2-Project/Contributing/Code-Style-Language-Versions.html#id4
quote-style = "single"


[lint]
extend-select = [
    # pycodestyle, as it is used by ROS package ament_pycodestyle to check style
    # https://docs.astral.sh/ruff/rules/#pycodestyle-e-w
    "E",
    # PEP8 Naming conventions
    # https://docs.astral.sh/ruff/rules/#pep8-naming-n
    "N",
]
```
